# add the following to _config.yml file
# other https://pages.github.com/themes/
title: Kyle Williams
#theme: jeykll-theme-hacker
logo: /assets/headshot_circle.png
#logo: /assets/Headshot2.png
remote_theme: pages-themes/minimal@v0.2.0
